name: 'Terraform'

on:
  push:
    branches: 
      - '**'

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    # Terraform Cloud
    #- name: Setup Terraform
    # uses: hashicorp/setup-terraform@v1
    #  with:
    #    cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_TKN }}
    
    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Check variables
      run: |
        export ARM_CLIENT_SECRET="${{ secrets.ARM_CLIENT_SECRET }}"
        echo $ARM_CLIENT_ID
        echo $ARM_CLIENT_SECRET
        echo $ARM_TENANT_ID
        echo $ARM_SUBSCRIPTION_ID
        echo $ARM_RG_ID
        
    #- name: Terraform Plan
    #  run: terraform plan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/"main"' && github.event_name == 'push'
      run: terraform apply -auto-approve -input=false
